const dict = {
    'es': {
        'Sign In': 'Ingresar',
        'Sign in': 'Ingresar',
        'Sign Up': 'Crear cuenta',
        'Sign Out': 'Desconectar',
        'Sign in to your account': 'Ingrese a su sesión',
        'Enter your email address': 'Ingrese su email',
        'Enter your password': 'Ingrese su contraseña',
        'Forgot your password?': 'Olvidaste tu contraseña',
        'Email Address *': 'Email',
        'Lost your code?': 'Perdió su código?',
        'Resend Code': 'Reenviar código',
        'Confirm Sign up': 'Confirmar registro',
        Username: 'Nombre de usuario',
        "Password *": 'Contraseña',
        "Reset password": 'Resetea tu contraseña',
        "Reset your password": 'Resetea tu contraseña',
        "No account?": 'No tienes cuenta?',
        "Create account": 'Crear cuenta',
        "Have an account?": 'Tienes cuenta?',
        'Change Password': 'Cambia la contraseña',
        'Password': 'Contraseña',
        'Phone Number *': 'Teléfono',
        'CREATE ACCOUNT': 'Crear cuenta',
        'New Password': 'Nueva contraseña',
        Email: 'Email',
        'Phone Number': 'Número de teléfono',
        'Confirm a Code': 'Confirmar un código',
        'Confirm Sign In': 'Confirmar inicio de sesión',
        'Confirm Sign Up': 'Confirmar Registrarse',
        'Back to Sign In': 'Volver a Iniciar sesión',
        'Send Code': 'Enviar código',
        Confirm: 'Confirmar',
        'Resend a Code': 'Reenviar un código',
        Submit: 'Enviar',
        Skip: 'Omitir',
        Verify: 'Verificar',
        'Verify Contact': 'Verificar contacto',
        Code: 'Código',
        'Account recovery requires verified contact information':
            'La recuperación de la cuenta requiere información de contacto verificada',

        'User does not exist': 'el usuario no existe',
        'User already exists': 'El usuario ya existe',
        'Incorrect username or password':
            'Nombre de usuario o contraseña incorrecta',
        'Invalid password format': 'Formato de contraseña inválido',
        'Invalid phone number format': `Formato de número de teléfono inválido.
  Utilice el formato de número de teléfono +12345678900`,
    },
};
export default dict;
